on:
  workflow_dispatch:
  schedule:
    - cron: '45 8,20 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay/it1h-0@cron
        with:
          token: ${{ secrets.token }}
